name: dslink_rest
description: REST Server DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  http_multi_server: "^2.0.3"
  mustache4dart: "^1.0.10"
  mime: "^0.9.3"
